name: tournament
description: $description
version: '${version}'

main: xyz.pyxismc.tournament.paper.TournamentPaperPlugin
api-version: '1.21'
load: STARTUP

authors: [ IceLoup ]
website: https://pyxismc.xyz

depend: []
softdepend: [PlaceholderAPI]